/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TinKhuyenMaiIdRouteImport } from './routes/tin-khuyen-mai.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TinKhuyenMaiIdRoute = TinKhuyenMaiIdRouteImport.update({
  id: '/tin-khuyen-mai/$id',
  path: '/tin-khuyen-mai/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tin-khuyen-mai/$id': typeof TinKhuyenMaiIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tin-khuyen-mai/$id': typeof TinKhuyenMaiIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tin-khuyen-mai/$id': typeof TinKhuyenMaiIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tin-khuyen-mai/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tin-khuyen-mai/$id'
  id: '__root__' | '/' | '/tin-khuyen-mai/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TinKhuyenMaiIdRoute: typeof TinKhuyenMaiIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tin-khuyen-mai/$id': {
      id: '/tin-khuyen-mai/$id'
      path: '/tin-khuyen-mai/$id'
      fullPath: '/tin-khuyen-mai/$id'
      preLoaderRoute: typeof TinKhuyenMaiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TinKhuyenMaiIdRoute: TinKhuyenMaiIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
